# Generated by Django 5.0.3 on 2024-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
