# Generated by Django 5.0.3 on 2024-10-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0004_product_discount_delete_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
