# Generated by Django 5.0.3 on 2024-10-22 05:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0007_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
