# Generated by Django 5.0.3 on 2024-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0008_notification_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
