# Generated by Django 5.0.3 on 2024-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0010_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
