# Generated by Django 5.0.3 on 2024-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0012_alter_product_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='origins',
            field=models.ManyToManyField(related_name='products', to='cosmetics.origin'),
        ),
    ]
