# Generated by Django 5.0.3 on 2024-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0017_blog_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='promotionticket',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rulesofpromotionticket',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='PromotionTicket',
        ),
        migrations.DeleteModel(
            name='RulesOfPromotionTicket',
        ),
    ]
