# Generated by Django 5.0.3 on 2024-11-05 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0018_remove_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('name', models.CharField(choices=[('Thanh toán khi nhận hàng', 'Cod'), ('Thanh toán bằng thẻ ATM nội địa', 'Atm'), ('Chuyển khoản', 'Internet Banking'), ('Thanh toán thẻ Visa/MasterCard', 'Visa Master')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('name', models.CharField(choices=[('Nhận tại cửa hàng', 'On Site'), ('Giao hàng tận nơi', 'Delivery')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('ward', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='cosmetics.OrderDetail', to='cosmetics.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.payment'),
        ),
        migrations.CreateModel(
            name='PromotionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('orders', models.ManyToManyField(related_name='promotion_tickets', to='cosmetics.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RulesOfPromotionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.promotionticket')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.shipment'),
        ),
    ]
