# Generated by Django 5.0.3 on 2024-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0019_payment_shipment_order_orderdetail_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionticket',
            name='orders',
        ),
        migrations.AddField(
            model_name='promotionticket',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promotionticket',
            name='min_order_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='RulesOfPromotionTicket',
        ),
    ]
