# Generated by Django 5.0.3 on 2024-11-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0020_remove_promotionticket_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
