# Generated by Django 5.0.3 on 2024-11-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0021_order_total_amount_orderdetail_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='discount_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
