# Generated by Django 5.0.3 on 2024-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0022_order_shipping_fee_order_vat_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
