# Generated by Django 5.0.3 on 2024-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0024_order_temp_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
