# Generated by Django 5.0.3 on 2024-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0028_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origins',
            field=models.ManyToManyField(null=True, related_name='products', to='cosmetics.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='products', to='cosmetics.tag'),
        ),
    ]
