# Generated by Django 5.0.3 on 2024-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0029_alter_product_origins_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origins',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='cosmetics.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='cosmetics.tag'),
        ),
    ]
