# Generated by Django 5.0.3 on 2024-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0033_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionticket',
            name='expiry_number_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotionticket',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
