# Generated by Django 5.0.3 on 2024-11-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0034_promotionticket_expiry_number_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmetics.promotionticket'),
        ),
        migrations.AddField(
            model_name='promotionticket',
            name='discount_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
