# Generated by Django 5.0.3 on 2024-11-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0035_order_promotion_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
