# Generated by Django 5.0.3 on 2024-11-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0037_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PROCESSING', 'Đang xử lý'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao hàng'), ('CANCELLED', 'Đã hủy'), ('RETURNED', 'Hoàn trả'), ('REFUNDED', 'Hoàn tiền'), ('FAILED', 'Thất bại')], default='Chờ xác nhận', max_length=20, null=True),
        ),
    ]
