# Generated by Django 5.0.3 on 2024-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0041_event_eventdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
