version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecosmetics_django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ecosmetics.settings
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: shineecommercedb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456a@A

  db:
    image: mysql:8.0
    container_name: ecosmetics_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@A
      MYSQL_DATABASE: shineecommercedb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456a@A
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
